### ISSUE TITLE
Application won't start if JAVA_HOME points to Java8 on Windows

### ISSUE THREAD

**Issue by antoine-guillou** [binjr/binjr#111]
I installed the latest binjr v3.0.1 via the .msi on Windows10 and I got an error very similar to:
https://stackoverflow.com/questions/59848805/exception-in-thread-windowsnativerunloopthread-java-lang-nosuchmethoderror-i

Removing the JAVA_HOME variable fixed the issue.

**Comment by fthevenet** [comment]
Hi, 

Thanks for reporting that issue. 
That's not something I've come across before, even though I have many version of the JDK installed on my Windows machine, and keep changing the value of `JAVA_HOME` depending on my needs.
Could you please post the beginning of the binjr log file from the session you encountered the issue, if it is still present? I would like to check what was the java home as determined by the app.

**Comment by fthevenet** [comment]
Also, could you please detail what are the versions and vendors of the other installations
 of the JDK present on your machine?

**Comment by antoine-guillou** [comment]
This is the beginning of the log file when the application cannot start (it hangs on the splash screen):

[2021-04-21 17:30:41.458] [ERROR] [WindowsNativeRunloopThread] [stderr] Exception in thread "WindowsNativeRunloopThread" 
[2021-04-21 17:30:41.462] [ERROR] [WindowsNativeRunloopThread] [stderr] java.lang.NoSuchMethodError: <init>
[2021-04-21 17:30:41.463] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
[2021-04-21 17:30:41.463] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)
[2021-04-21 17:30:41.463] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
[2021-04-21 17:30:41.465] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
[2021-04-21 17:30:41.465] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
[2021-04-21 17:30:41.465] [ERROR] [WindowsNativeRunloopThread] [stderr] 	at java.base/java.lang.Thread.run(Unknown Source)


This is the beginning of the log file when the application starts (after removing my JAVA_HOME):

[2021-04-21 17:48:21.539] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] ***********************************
[2021-04-21 17:48:21.544] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] *  Starting binjr
[2021-04-21 17:48:21.545] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] ***********************************
[2021-04-21 17:48:21.558] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Version=3.0.1 (build #20210406.2)
[2021-04-21 17:48:21.558] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Java Version=16
[2021-04-21 17:48:21.560] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] JavaFX Version=16
[2021-04-21 17:48:21.564] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Java Vendor=Azul Systems, Inc.
[2021-04-21 17:48:21.564] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Java VM name=OpenJDK 64-Bit Server VM (16+36)
[2021-04-21 17:48:21.570] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Java Home=C:\Users\guill\AppData\Local\binjr\runtime
[2021-04-21 17:48:21.573] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] Operating System=Windows 10 (10.0)
[2021-04-21 17:48:21.575] [INFO ] [JavaFX Application Thread] [eu.binjr.core.Binjr] System Architecture=amd64

When the application cannot start, my JAVA_HOME resolves to C:\Program Files\Java\jdk1.8.0_231\jre which is an Oracle version.

**Comment by fthevenet** [comment]
I installed the latest Oracle JRE 8 to try and reproduce, but to no avail.
I don't think the root cause in your case is the app actually trying to load using the JRE 8, otherwise you'd get an `UnsupportedClassVersionError`, as the jars targets Java 11.
But with that said, I don't know what is actually going wrong.

If you start `binjr.exe` from the command line, you should see the logs from the native launcher (the one initializing the JVM) displayed to the standard output, like so:
``` 
$C:\Users\fred\AppData\Local\binjr\binjr.exe

[info] Module Name: C:\Users\fred\AppData\Local\binjr\binjr.exe
[info] Module INI: C:\Users\fred\AppData\Local\binjr\binjr.ini
[info] Module Dir: C:\Users\fred\AppData\Local\binjr\
[info] INI Dir: C:\Users\fred\AppData\Local\binjr\
[info] Displaying embedded splash image
[info] Configured vm.location: .\runtime\bin\server\jvm.dll
[info] Found VM: C:\Users\fred\AppData\Local\binjr\runtime\bin\server\jvm.dll
[info] Expanding Classpath: .\libs\*
...
```

Maybe this could shed some light?

**Comment by antoine-guillou** [comment]
I think that my issue might be related to this:
https://stackoverflow.com/questions/51101481/nosuchmethoderror-init-in-com-sun-glass-ui-win-winapplication-staticscreen-ge

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr] Exception in thread "WindowsNativeRunloopThread"
[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr] java.lang.NoSuchMethodError: <init>

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr]         at java.base/java.lang.Thread.run(Unknown Source)

[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr] Exception in thread "WindowsNativeRunloopThread"
[2021-04-26 10:57:30.501] [ERROR] [WindowsNativeRunloopThread] [stderr] java.lang.NoSuchMethodError: <init>

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)

[2021-04-26 10:57:30.511] [ERROR] [WindowsNativeRunloopThread] [stderr]         at java.base/java.lang.Thread.run(Unknown Source)

[2021-04-26 10:57:30.517] [ERROR] [JavaFX Application Thread] [stderr] Exception in thread "JavaFX Application Thread"
[2021-04-26 10:57:30.517] [ERROR] [JavaFX Application Thread] [stderr] java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Screen.getNativeScreen()" because "<parameter1>" is null

[2021-04-26 10:57:30.517] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(Unknown Source)

[2021-04-26 10:57:30.517] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(Unknown Source)

[2021-04-26 10:57:30.517] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(Unknown Source)

[2021-04-26 10:57:30.521] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(Unknown Source)

[2021-04-26 10:57:30.521] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)

[2021-04-26 10:57:30.521] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

[2021-04-26 10:57:30.521] [ERROR] [JavaFX Application Thread] [stderr]  at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)

[2021-04-26 10:57:30.521] [ERROR] [JavaFX Application Thread] [stderr]  at java.base/java.lang.Thread.run(Unknown Source)

**Comment by fthevenet** [comment]
It looks like the same issue indeed.
Interestingly, I can actually see that in my case the glass.dll is also (and incorrectly) loaded from the Oracle JRE distro:
![image](https://user-images.githubusercontent.com/7450507/116071238-ee16c000-a68d-11eb-9e77-b45150d2df63.png)
 ... but since the app starts and appear to work in my case, I assume that the version I got (1.8.0_291) was updated to back-port recent modifications from OpenJFX, whereas the one you use (231) was not.

At any rate, there's unfortunately not much I can do on my end apart from documenting the workaround in the "troubleshooting" section of the site.

**Comment by antoine-guillou** [comment]
I can confirm that it works if I update my Java8 to 1.8.0_291.
Thanks for digging into it!

**Comment by fthevenet** [comment]
I actually dug some more and it looks like there is a way to avoid the issue, by moving the launcher executable in the same folder as the dlls, as Windows' always favor loading dlls from the same folder as the app before starting looking somewhere else [1].
I've done some preliminary tests and it does look to behave as intended, but I need to make sure it doesn't break something else.

[1] https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order
