### ISSUE TITLE
Cannot open demo workspace

### ISSUE THREAD

**Issue by mikehearn** [binjr/binjr#118]
With binjr from git master, when opening the demo adapter workspace with plugin installed I get:

```
[2022-05-03 18:40:00.567] [ERROR] [AppKit Thread] [eu.binjr.core.controllers.MainViewController] Error loading time series
javafx.fxml.LoadException:
file:/Users/mike/Upstreams/binjr/build/app_image/binjr-3.8.0-SNAPSHOT_mac-x86_64/3.8.0-SNAPSHOT/libs/binjr-core-3.8.0-SNAPSHOT.jar!/eu/binjr/views/XYChartsWorksheetView.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.load(Unknown Source) ~[javafx.fxml:?]
	at eu.binjr.core.controllers.MainViewController.loadWorksheet(MainViewController.java:1082) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.MainViewController.loadWorksheetInTab(MainViewController.java:1159) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.MainViewController.loadWorksheet(MainViewController.java:1022) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.MainViewController.loadWorksheets(MainViewController.java:807) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.MainViewController.lambda$loadWorkspace$41(MainViewController.java:781) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) ~[javafx.base:?]
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) ~[javafx.base:?]
	at javafx.event.Event.fireEvent(Unknown Source) ~[javafx.base:?]
	at javafx.concurrent.EventHelper.fireEvent(Unknown Source) ~[javafx.graphics:?]
	at javafx.concurrent.Task.fireEvent(Unknown Source) ~[javafx.graphics:?]
	at javafx.concurrent.Task.setState(Unknown Source) ~[javafx.graphics:?]
	at javafx.concurrent.Task$TaskCallable.lambda$call$1(Unknown Source) ~[javafx.graphics:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[javafx.graphics:?]
	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[javafx.graphics:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[javafx.graphics:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "javafx.fxml.FXMLLoader.getClassLoader()" is null
	at javafx.fxml.FXMLLoader.loadTypeForPackage(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.loadType(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.importClass(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.processImport(Unknown Source) ~[javafx.fxml:?]
	at javafx.fxml.FXMLLoader.processProcessingInstruction(Unknown Source) ~[javafx.fxml:?]
	... 24 more
[2022-05-03 18:40:00.575] [ERROR] [AppKit Thread] [eu.binjr.core.dialogs.Dialogs] Failed to load worksheet CPU usage & Memory: Cannot invoke "eu.binjr.common.javafx.controls.TimeRangePicker.selectedRangeProperty()" because "this.timeRangePicker" is null - Failed to load worksheet CPU usage & Memory: Cannot invoke "eu.binjr.common.javafx.controls.TimeRangePicker.selectedRangeProperty()" because "this.timeRangePicker" is null
```

**Comment by fthevenet** [comment]
Hi,

I tried but failed to reproduce the issue on Windows (I don't have any other platform handy at the moment).
Can you please confirm that you are using the latest version of the demo plugin ([v3.0.0](https://github.com/binjr/binjr-adapter-demo/releases/download/v3.0.0/binjr-adapter-demo-3.0.0.zip))?

**Comment by mikehearn** [comment]
Yep, I am. I ran: 

```
gradle prepareAppBundle
mkdir build/app_image/binjr-3.8.0-SNAPSHOT_mac-x86_64/3.8.0-SNAPSHOT/plugins
cd build/app_image/binjr-3.8.0-SNAPSHOT_mac-x86_64/3.8.0-SNAPSHOT/plugins
unzip ~/Downloads/binjr-adapter-demo-3.0.0.jar
cd ..
./binjr
```

then went and opened the `demo.bjr` file in the plugins directory. It looks like a classloader issue? Maybe I'm not meant to run the app when it's been packaged in this way? I'm sort of guessing how to combine a git build with the plugins directory. How do you run it with plugins?

**Comment by mikehearn** [comment]
There's something pretty clearly very wrong with what I'm doing. Even after adding loader.setClassLoader calls, it gets further but then dies with:

```
Caused by: java.lang.IllegalArgumentException: Property  is not managed by this instance of BindingManager
	at eu.binjr.common.javafx.bindings.BindingManager.resume(BindingManager.java:283) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.XYChartsWorksheetController.setEditChartMode(XYChartsWorksheetController.java:284) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.WorksheetController.initialize(WorksheetController.java:185) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	at eu.binjr.core.controllers.XYChartsWorksheetController.initialize(XYChartsWorksheetController.java:270) ~[binjr-core-3.8.0-SNAPSHOT.jar:3.8.0-SNAPSHOT]
	... 24 more
```

Maybe I'm using the wrong version of Java, or something like that? I'm running on Java 17.

**Comment by mikehearn** [comment]
Yeah, it's definitely something weird to do with using incomplete packaging. Looking at the startup script there's a flag to determine where it looks for plugins. I tried `gradle run --args=--system-plugins-path=$PWD/plugins` and that works. 

The output of that task looked like it was meant to be executable but I guess there's something missing.

**Comment by fthevenet** [comment]
Yes, you must specify the path to load built-in plugins from using the  `--system-plugins-path`  arg.
But normally the startup script already does that, and if I understand the script you listed 2 posts above, this is what you use to bootstrap the app, isn't it?
Maybe there's something else specific done in some later tasks (I haven't had to touch the build in a while, so I don't know off the top of my head); you could try to run `sh gradlew clean packageAsTar` as this task is meant to produce a complete package (build time might be slightly  longer due to generation of the archive, though not significantly).
