### ISSUE TITLE
HTTP over TLS is broken

### ISSUE THREAD

**Issue by fthevenet** [binjr/binjr#47]
```
[2019-01-13 17:08:49.141] [DEBUG] [binjr-async-thread-1] [eu.binjr.common.github.GithubApi] requestUrl = https://api.github.com/repos/binjr/binjr/releases/latest
[2019-01-13 17:08:49.524] [ERROR] [JavaFX Application Thread] [eu.binjr.core.preferences.UpdateManager] Error while checking for update
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]
	at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source) ~[?:?]
	at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165) ~[httpclient-4.5.6.jar:4.5.6]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[httpclient-4.5.6.jar:4.5.6]
	at eu.binjr.common.github.GithubApi.getRelease(GithubApi.java:103) ~[binjr-core-2.2.2-SNAPSHOT.jar:2.2.2-SNAPSHOT]
	at eu.binjr.common.github.GithubApi.getLatestRelease(GithubApi.java:80) ~[binjr-core-2.2.2-SNAPSHOT.jar:2.2.2-SNAPSHOT]
	at eu.binjr.core.preferences.UpdateManager$1.call(UpdateManager.java:117) ~[binjr-core-2.2.2-SNAPSHOT.jar:2.2.2-SNAPSHOT]
	at eu.binjr.core.preferences.UpdateManager$1.call(UpdateManager.java:113) ~[binjr-core-2.2.2-SNAPSHOT.jar:2.2.2-SNAPSHOT]
	at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[javafx.graphics:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by fthevenet** [comment]
Probably caused by a missing module in the packaged JRE, as it seems to work fine when run from a full JDK.

**Comment by fthevenet** [comment]
So as  it turned out that this issue had the potential to affect all https traffic.  
Root cause was indeed missing modules in the jlinked image, namely `jdk.crypto.ec` and `dk.crypto.cryptoki`, which allow exposing extra crypto algorithm to the jre, which is this case where required to honor the TLS handshake.
